name: pr
on:
  pull_request: {}

jobs:
  format:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup clang-format
      run: sudo apt install clang-format
    - name: Run clang-format
      run: |
        git fetch
        git clang-format-9 -v --style file origin/${{ github.base_ref }}
    - name: Commit changes
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: Apply formatting changes
        branch: ${{ github.head_ref }}
